#!/bin/bash

set -e

. colors

# Definition of the patterns to colorize
REV_REGEX='\(^revision[[:space:]][0-9\.]*\)'
REV_COLOR="${TXTRED}\1${TXTRST}"

WF_REGEX='\(^Working file: [a-zA-Z0-9\._]*\)'
WF_COLOR="${TXTBLU}\1${TXTRST}"

# Substitution
cvs log "$@" | sed "s/${REV_REGEX}/${REV_COLOR}/
s/${WF_REGEX}/${WF_COLOR}/" | less -R
