#!/bin/bash

set -e

. colors

LINE_REGEX='(^File:)'

# Definition of the patterns to colorize
STA_REGEX='\(Status:\)'
STA_COLOR="${TXTRED}\1${TXTRST}"

WRV_REGEX='\([[:digit:]].[[:digit:]]\)'
WRV_COLOR="${TXTYLW}\1${TXTRST}"

UTD_REGEX='\(Up-to-date\)'
UTD_COLOR="${TXTBLU}\1${TXTRST}"

LRM_REGEX='\(Locally Removed\)'
LRM_COLOR="${TXTGRN}\1${TXTRST}"

LAD_REGEX='\(Locally Added\)'
LAD_COLOR="${TXTBLD}${TXTRED}\1${TXTRST}"

LMO_REGEX='\(Locally Modified\)'
LMO_COLOR="${TXTBLD}${TXTYLW}\1${TXTRST}"


# Substitution
cvs status "$@" | grep -E $LINE_REGEX | sed "s/${STA_REGEX}/${STA_COLOR}/
s/${UTD_REGEX}/${UTD_COLOR}/
s/${LRM_REGEX}/${LRM_COLOR}/
s/${LAD_REGEX}/${LAD_COLOR}/
s/${LMO_REGEX}/${LMO_COLOR}/
"
# s/${WRV_REGEX}/${WRV_COLOR}/

