#!/bin/bash

set -e

. colors

# Definition of the patterns to colorize
REV_REGEX='\(^revision\s[0-9\.]*\)'
REV_COLOR="${TXTRED}\1${TXTRST}"

WF_REGEX='\(^Working file:\s[a-zA-Z_\/\.]*\)'
WF_COLOR="${TXTBLU}\1${TXTRST}"

# Substitution
cvs log "$@" | sed "s/${REV_REGEX}/${REV_COLOR}/
s/${WF_REGEX}/${WF_COLOR}/" | less -R
